server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://thejudgement-db-rds.cexmlygcy72v.ap-northeast-2.rds.amazonaws.com:3306/theJudgement_db
    username: ignisAdmin
    password: dlrmsltm21
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전